### PR TITLE
Include kubebit

### PR DESCRIPTION
**Pull request by khaosdoctor**
I've separated the bit from the Kubernetes drawing on the BIT_KUBERNETES file so we can use it separately.

### CODE REVIEW

**Comment by SandraAhlgrimm** [comment]
Hi Lucas, thanks for your contribution. Is it possible to come up with a more descriptive file name? BIT-something might be misleading as Bit is not involved.

**Comment by khaosdoctor** [comment]
Sure thing! Let me change it here

**Comment by khaosdoctor** [comment]
I renamed it to `kubernetes-alt` since there's already a kubernetes one.

**Comment by SandraAhlgrimm** [comment]
LGTM

**Pull request closed without merging**
